### ISSUE TITLE
GraphhopperManager lambda config mismatch

### ISSUE THREAD

**Issue by sperka** [aws-samples/aws-last-mile-delivery-hyperlocal#29]
`packages/@prototype/simulator/src/SimulatorManagerStack/GraphhopperManager/@lambda/src/index.js`
runTask uses `config.securityGroups`, while config exposes `securityGroup`

also, in CDKv2 we pass `securityGroupId`, to investigate if that's ok to use in the lambda

**Comment by mirgj** [comment]
closed by #39
